package Vista;

import com.toedter.calendar.JDateChooser;
import com.toedter.components.JSpinField;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.JToolBar;
import java.util.Calendar;

/**
 *
 * @author Panto
 */
public class Form_Alquiler extends javax.swing.JInternalFrame {

    /**
     * Creates new form Form_Cliente
     */
    public Form_Alquiler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        group_rdb = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_registrar = new javax.swing.JButton();
        cmb_maquinaria = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_desc = new javax.swing.JTextField();
        lb_nom = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        lb_tel = new javax.swing.JLabel();
        LB_NOMBRE = new javax.swing.JLabel();
        LB_TELEFONO = new javax.swing.JLabel();
        LB_IDENTIFICACION = new javax.swing.JLabel();
        lb_cant = new javax.swing.JLabel();
        lb_desc = new javax.swing.JLabel();
        LB_DESCRIPCION = new javax.swing.JLabel();
        LB_CANTIDAD = new javax.swing.JLabel();
        LB_TIPO = new javax.swing.JLabel();
        lb_tip = new javax.swing.JLabel();
        cmb_cliente = new javax.swing.JComboBox<>();
        btn_agregar = new javax.swing.JButton();
        rdb_pesada = new javax.swing.JRadioButton();
        rdb_general = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_dias = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_no = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        spin_hour = new com.toedter.components.JSpinField();
        spin_min = new com.toedter.components.JSpinField();
        spin_seg = new com.toedter.components.JSpinField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        LB_CANTIDAD1 = new javax.swing.JLabel();
        lb_entrega = new javax.swing.JLabel();
        LB_CANTIDAD2 = new javax.swing.JLabel();
        lb_total = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Cliente:");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Maquinaria:");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Fecha:");

        btn_registrar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        cmb_maquinaria.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cmb_maquinaria.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        cmb_maquinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_maquinariaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Descripción:");

        txt_desc.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        lb_nom.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_nom.setText("-----");

        lb_id.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_id.setText("-----");

        lb_tel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_tel.setText("------");

        LB_NOMBRE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        LB_NOMBRE.setText("Nombre");

        LB_TELEFONO.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        LB_TELEFONO.setText("Teléfono");

        LB_IDENTIFICACION.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        LB_IDENTIFICACION.setText("Identificación");

        lb_cant.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_cant.setText("-----");

        lb_desc.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_desc.setText("-----");

        LB_DESCRIPCION.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        LB_DESCRIPCION.setText("Descripción");

        LB_CANTIDAD.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        LB_CANTIDAD.setText("Cantidad");

        LB_TIPO.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        LB_TIPO.setText("Tipo");

        lb_tip.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_tip.setText("-----");

        cmb_cliente.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cmb_cliente.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        cmb_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_clienteActionPerformed(evt);
            }
        });

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Icons/ico_+.png"))); // NOI18N

        group_rdb.add(rdb_pesada);
        rdb_pesada.setText("Pesada");
        rdb_pesada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_pesadaActionPerformed(evt);
            }
        });

        group_rdb.add(rdb_general);
        rdb_general.setText("General");
        rdb_general.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_generalActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Días:");

        txt_dias.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setText("No.");

        txt_no.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel8.setText("Hora");

        jLabel9.setText("Min");

        jLabel10.setText("Seg");

        LB_CANTIDAD1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        LB_CANTIDAD1.setText("Entregar:");

        lb_entrega.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_entrega.setText("-----");

        LB_CANTIDAD2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        LB_CANTIDAD2.setText("Total:");

        lb_total.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_total.setText("-----");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LB_CANTIDAD)
                                        .addGap(80, 80, 80))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lb_cant)
                                        .addGap(95, 95, 95)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LB_DESCRIPCION)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lb_desc)
                                        .addGap(25, 25, 25))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdb_pesada)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rdb_general))
                                    .addComponent(cmb_maquinaria, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_no, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spin_seg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(6, 6, 6)
                                            .addComponent(spin_hour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(5, 5, 5)
                                            .addComponent(spin_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_cliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_dias, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_desc)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LB_CANTIDAD2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lb_total))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LB_CANTIDAD1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lb_entrega))))
                            .addComponent(LB_TIPO)
                            .addComponent(lb_tip)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(LB_NOMBRE)
                                        .addGap(70, 70, 70)
                                        .addComponent(LB_IDENTIFICACION)
                                        .addGap(64, 64, 64))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(lb_nom)
                                        .addGap(112, 112, 112)
                                        .addComponent(lb_id)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LB_TELEFONO)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lb_tel)
                                        .addGap(11, 11, 11)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(txt_no, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spin_hour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel8)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(spin_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(spin_seg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel9)
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel10))))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dias, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_NOMBRE)
                    .addComponent(LB_TELEFONO)
                    .addComponent(LB_IDENTIFICACION))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lb_nom))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lb_id))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lb_tel)))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdb_pesada)
                    .addComponent(rdb_general))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cmb_maquinaria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LB_TIPO)
                            .addComponent(LB_DESCRIPCION)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(LB_CANTIDAD)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_tip)
                    .addComponent(lb_cant)
                    .addComponent(lb_desc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LB_CANTIDAD1)
                            .addComponent(lb_entrega))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LB_CANTIDAD2)
                            .addComponent(lb_total))))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void cmb_maquinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_maquinariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_maquinariaActionPerformed

    private void cmb_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_clienteActionPerformed

    private void rdb_pesadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_pesadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_pesadaActionPerformed

    private void rdb_generalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_generalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_generalActionPerformed


    public JButton getBtn_registrar() {
        return btn_registrar;
    }

    public void setBtn_registrar(JButton btn_registrar) {
        this.btn_registrar = btn_registrar;
    }

    public JComboBox<String> getCmb_cliente() {
        return cmb_cliente;
    }

    public void setCmb_cliente(JComboBox<String> cmb_cliente) {
        this.cmb_cliente = cmb_cliente;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    public void setjMenuItem1(JMenuItem jMenuItem1) {
        this.jMenuItem1 = jMenuItem1;
    }

    public JTextField getTxt_desc() {
        return txt_desc;
    }

    public void setTxt_desc(JTextField txt_desc) {
        this.txt_desc = txt_desc;
    }


    public JLabel getLB_IDENTIFICACION() {
        return LB_IDENTIFICACION;
    }

    public void setLB_IDENTIFICACION(JLabel LB_IDENTIFICACION) {
        this.LB_IDENTIFICACION = LB_IDENTIFICACION;
    }

    public JLabel getLB_NOMBRE() {
        return LB_NOMBRE;
    }

    public void setLB_NOMBRE(JLabel LB_NOMBRE) {
        this.LB_NOMBRE = LB_NOMBRE;
    }

    public JLabel getLB_TELEFONO() {
        return LB_TELEFONO;
    }

    public void setLB_TELEFONO(JLabel LB_TELEFONO) {
        this.LB_TELEFONO = LB_TELEFONO;
    }

    public JLabel getLb_id() {
        return lb_id;
    }

    public void setLb_id(JLabel lb_id) {
        this.lb_id = lb_id;
    }

    public JLabel getLb_nom() {
        return lb_nom;
    }

    public void setLb_nom(JLabel lb_nom) {
        this.lb_nom = lb_nom;
    }

    public JLabel getLb_tel() {
        return lb_tel;
    }

    public void setLb_tel(JLabel lb_tel) {
        this.lb_tel = lb_tel;
    }

    public JLabel getLB_CANTIDAD() {
        return LB_CANTIDAD;
    }

    public void setLB_CANTIDAD(JLabel LB_CANTIDAD) {
        this.LB_CANTIDAD = LB_CANTIDAD;
    }

    public JLabel getLB_DESCRIPCION() {
        return LB_DESCRIPCION;
    }

    public void setLB_DESCRIPCION(JLabel LB_DESCRIPCION) {
        this.LB_DESCRIPCION = LB_DESCRIPCION;
    }

    public JLabel getLB_TIPO() {
        return LB_TIPO;
    }

    public void setLB_TIPO(JLabel LB_TIPO) {
        this.LB_TIPO = LB_TIPO;
    }

    public JButton getBtn_agregar() {
        return btn_agregar;
    }

    public void setBtn_agregar(JButton btn_agregar) {
        this.btn_agregar = btn_agregar;
    }

    public JComboBox<String> getCmb_maquinaria() {
        return cmb_maquinaria;
    }

    public void setCmb_maquinaria(JComboBox<String> cmb_maquinaria) {
        this.cmb_maquinaria = cmb_maquinaria;
    }

    public JLabel getLb_cant() {
        return lb_cant;
    }

    public void setLb_cant(JLabel lb_cant) {
        this.lb_cant = lb_cant;
    }

    public JLabel getLb_desc() {
        return lb_desc;
    }

    public void setLb_desc(JLabel lb_desc) {
        this.lb_desc = lb_desc;
    }

    public JLabel getLb_tip() {
        return lb_tip;
    }

    public void setLb_tip(JLabel lb_tip) {
        this.lb_tip = lb_tip;
    }

    public JRadioButton getRdb_general() {
        return rdb_general;
    }

    public void setRdb_general(JRadioButton rdb_general) {
        this.rdb_general = rdb_general;
    }

    public JRadioButton getRdb_pesada() {
        return rdb_pesada;
    }

    public void setRdb_pesada(JRadioButton rdb_pesada) {
        this.rdb_pesada = rdb_pesada;
    }

    public ButtonGroup getGroup_rdb() {
        return group_rdb;
    }

    public void setGroup_rdb(ButtonGroup group_rdb) {
        this.group_rdb = group_rdb;
    }

    public JTextField getTxt_dias() {
        return txt_dias;
    }

    public void setTxt_dias(JTextField txt_dias) {
        this.txt_dias = txt_dias;
    }

    public JDateChooser getjDateChooser1() {
        return jDateChooser1;
    }

    public void setjDateChooser1(JDateChooser jDateChooser1) {
        this.jDateChooser1 = jDateChooser1;
    }

    public JTextField getTxt_no() {
        return txt_no;
    }

    public void setTxt_no(JTextField txt_no) {
        this.txt_no = txt_no;
    }

    public JSpinField getSpin_hour() {
        return spin_hour;
    }

    public void setSpin_hour(JSpinField spin_hour) {
        this.spin_hour = spin_hour;
    }

    public JSpinField getSpin_min() {
        return spin_min;
    }

    public void setSpin_min(JSpinField spin_min) {
        this.spin_min = spin_min;
    }

    public JSpinField getSpin_seg() {
        return spin_seg;
    }

    public void setSpin_seg(JSpinField spin_seg) {
        this.spin_seg = spin_seg;
    }

    public JLabel getLb_entrega() {
        return lb_entrega;
    }

    public void setLb_entrega(JLabel lb_entrega) {
        this.lb_entrega = lb_entrega;
    }

    public JLabel getLb_total() {
        return lb_total;
    }

    public void setLb_total(JLabel lb_total) {
        this.lb_total = lb_total;
    }
    
    
    
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LB_CANTIDAD;
    private javax.swing.JLabel LB_CANTIDAD1;
    private javax.swing.JLabel LB_CANTIDAD2;
    private javax.swing.JLabel LB_DESCRIPCION;
    private javax.swing.JLabel LB_IDENTIFICACION;
    private javax.swing.JLabel LB_NOMBRE;
    private javax.swing.JLabel LB_TELEFONO;
    private javax.swing.JLabel LB_TIPO;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JComboBox<String> cmb_cliente;
    private javax.swing.JComboBox<String> cmb_maquinaria;
    private javax.swing.ButtonGroup group_rdb;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_cant;
    private javax.swing.JLabel lb_desc;
    private javax.swing.JLabel lb_entrega;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_nom;
    private javax.swing.JLabel lb_tel;
    private javax.swing.JLabel lb_tip;
    private javax.swing.JLabel lb_total;
    private javax.swing.JRadioButton rdb_general;
    private javax.swing.JRadioButton rdb_pesada;
    private com.toedter.components.JSpinField spin_hour;
    private com.toedter.components.JSpinField spin_min;
    private com.toedter.components.JSpinField spin_seg;
    private javax.swing.JTextField txt_desc;
    private javax.swing.JTextField txt_dias;
    private javax.swing.JTextField txt_no;
    // End of variables declaration//GEN-END:variables
}
